language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test
      script: npm run lint
      name: "Lint"
    - stage: test
      script:
      - npm install typescript@3
      - npm test
      name: "TypeScript 3"
    - script:
      - npm install typescript@4
      - npm test
      name: "TypeScript 4"
    - stage: deploy
      provider: script
      # script: bash scripts/publish.sh
      script:
      - npm run dist
      - echo "DEPLOY"
      skip_cleanup: true
      # email: it@mural.co
      on:
        branch: master
